package zone.rong.loliasm.patches;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import zone.rong.loliasm.core.LoliLoadingPlugin;
import zone.rong.loliasm.core.LoliTransformer;

import static org.objectweb.asm.Opcodes.*;

/**
 *
 * This class contains class writers for patched UnpackedBakedQuad and UnpackedBakedQuad$Builder
 * defineClass not called here, pass raw byte[] back to {@link LoliTransformer#transform(String, String, byte[])}
 *
 * No optimizations here except for soft patching `int tintIndex` to `byte tintIndex` like other BakedQuad derivatives.
 * Essentially just patching for bytecode compatibility at the moment.
 *
 * TODO: canonize float[][][] when getClass() == UnpackedBakedQuad.class, might be incompatible with MysticalLib
 */
public final class UnpackedBakedQuadPatch {

    public static byte[] rewriteUnpackedBakedQuad(byte[] originalClass) {
        ClassWriter writer = new ClassWriter(0);
        FieldVisitor fieldVisitor;
        MethodVisitor methodVisitor;

        writer.visit(52, ACC_PUBLIC | ACC_SUPER, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", null, "net/minecraft/client/renderer/block/model/BakedQuad", null);

        writer.visitSource("UnpackedBakedQuad.java", null);

        writer.visitInnerClass("net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "Builder", ACC_PUBLIC | ACC_STATIC);

        {
            fieldVisitor = writer.visitField(ACC_PROTECTED | ACC_FINAL, "unpackedData", "[[[F", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PROTECTED | ACC_FINAL, "tint", "B", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PROTECTED | ACC_FINAL, "orientation", "Lnet/minecraft/util/EnumFacing;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PROTECTED | ACC_FINAL, "applyDiffuseLighting", "Z", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PROTECTED, "packed", "Z", null, null);
            fieldVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "<init>", "([[[FILnet/minecraft/util/EnumFacing;Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;ZLnet/minecraft/client/renderer/vertex/VertexFormat;)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(20, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getSize" : "func_177338_f", "()I", false);
            methodVisitor.visitIntInsn(NEWARRAY, T_INT);
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/block/model/BakedQuad", "<init>", "([ILnet/minecraft/client/renderer/texture/TextureAtlasSprite;Lnet/minecraft/client/renderer/vertex/VertexFormat;)V", false);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(17, l1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "packed", "Z");
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLineNumber(21, l2);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "unpackedData", "[[[F");
            Label l3 = new Label();
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLineNumber(22, l3);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ILOAD, 2);
            methodVisitor.visitInsn(I2B);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "tint", "B");
            Label l4 = new Label();
            methodVisitor.visitLabel(l4);
            methodVisitor.visitLineNumber(23, l4);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "orientation", "Lnet/minecraft/util/EnumFacing;");
            Label l5 = new Label();
            methodVisitor.visitLabel(l5);
            methodVisitor.visitLineNumber(24, l5);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "applyDiffuseLighting", "Z");
            Label l6 = new Label();
            methodVisitor.visitLabel(l6);
            methodVisitor.visitLineNumber(25, l6);
            methodVisitor.visitInsn(RETURN);
            Label l7 = new Label();
            methodVisitor.visitLabel(l7);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l7, 0);
            methodVisitor.visitLocalVariable("unpackedData", "[[[F", null, l0, l7, 1);
            methodVisitor.visitLocalVariable("tint", "I", null, l0, l7, 2);
            methodVisitor.visitLocalVariable("orientation", "Lnet/minecraft/util/EnumFacing;", null, l0, l7, 3);
            methodVisitor.visitLocalVariable("texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;", null, l0, l7, 4);
            methodVisitor.visitLocalVariable("applyDiffuseLighting", "Z", null, l0, l7, 5);
            methodVisitor.visitLocalVariable("format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;", null, l0, l7, 6);
            methodVisitor.visitMaxs(4, 7);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, LoliLoadingPlugin.isDeobf ? "getVertexData" : "func_178209_a", "()[I", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(29, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "packed", "Z");
            Label l1 = new Label();
            methodVisitor.visitJumpInsn(IFNE, l1);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLineNumber(30, l2);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "packed", "Z");
            Label l3 = new Label();
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLineNumber(31, l3);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 1);
            Label l4 = new Label();
            methodVisitor.visitLabel(l4);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitInsn(ICONST_4);
            methodVisitor.visitJumpInsn(IF_ICMPGE, l1);
            Label l5 = new Label();
            methodVisitor.visitLabel(l5);
            methodVisitor.visitLineNumber(32, l5);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 2);
            Label l6 = new Label();
            methodVisitor.visitLabel(l6);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            Label l7 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l7);
            Label l8 = new Label();
            methodVisitor.visitLabel(l8);
            methodVisitor.visitLineNumber(33, l8);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 2);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", LoliLoadingPlugin.isDeobf ? "vertexData" : "field_178215_a", "[I");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitVarInsn(ILOAD, 2);
            methodVisitor.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/client/model/pipeline/LightUtil", "pack", "([F[ILnet/minecraft/client/renderer/vertex/VertexFormat;II)V", false);
            Label l9 = new Label();
            methodVisitor.visitLabel(l9);
            methodVisitor.visitLineNumber(32, l9);
            methodVisitor.visitIincInsn(2, 1);
            methodVisitor.visitJumpInsn(GOTO, l6);
            methodVisitor.visitLabel(l7);
            methodVisitor.visitLineNumber(31, l7);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitIincInsn(1, 1);
            methodVisitor.visitJumpInsn(GOTO, l4);
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(37, l1);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", LoliLoadingPlugin.isDeobf ? "vertexData" : "field_178215_a", "[I");
            methodVisitor.visitInsn(ARETURN);
            Label l10 = new Label();
            methodVisitor.visitLabel(l10);
            methodVisitor.visitLocalVariable("e", "I", null, l6, l7, 2);
            methodVisitor.visitLocalVariable("v", "I", null, l4, l1, 1);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l10, 0);
            methodVisitor.visitMaxs(5, 3);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "pipe", "(Lnet/minecraftforge/client/model/pipeline/IVertexConsumer;)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(42, l0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "getVertexFormat", "()Lnet/minecraft/client/renderer/vertex/VertexFormat;", true);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/client/model/pipeline/LightUtil", "mapFormats", "(Lnet/minecraft/client/renderer/vertex/VertexFormat;Lnet/minecraft/client/renderer/vertex/VertexFormat;)[I", false);
            methodVisitor.visitVarInsn(ASTORE, 2);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(43, l1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", LoliLoadingPlugin.isDeobf ? "hasTintIndex" : "func_178212_b", "()Z", false);
            Label l2 = new Label();
            methodVisitor.visitJumpInsn(IFEQ, l2);
            Label l3 = new Label();
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLineNumber(44, l3);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", LoliLoadingPlugin.isDeobf ? "getTintIndex" : "func_178211_c", "()I", false);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "setQuadTint", "(I)V", true);
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLineNumber(46, l2);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{"[I"}, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", LoliLoadingPlugin.isDeobf ? "getSprite" : "func_187508_a", "()Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;", false);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "setTexture", "(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;)V", true);
            Label l4 = new Label();
            methodVisitor.visitLabel(l4);
            methodVisitor.visitLineNumber(47, l4);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "applyDiffuseLighting", "Z");
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "setApplyDiffuseLighting", "(Z)V", true);
            Label l5 = new Label();
            methodVisitor.visitLabel(l5);
            methodVisitor.visitLineNumber(48, l5);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "orientation", "Lnet/minecraft/util/EnumFacing;");
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "setQuadOrientation", "(Lnet/minecraft/util/EnumFacing;)V", true);
            Label l6 = new Label();
            methodVisitor.visitLabel(l6);
            methodVisitor.visitLineNumber(49, l6);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 3);
            Label l7 = new Label();
            methodVisitor.visitLabel(l7);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitInsn(ICONST_4);
            Label l8 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l8);
            Label l9 = new Label();
            methodVisitor.visitLabel(l9);
            methodVisitor.visitLineNumber(50, l9);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 4);
            Label l10 = new Label();
            methodVisitor.visitLabel(l10);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "getVertexFormat", "()Lnet/minecraft/client/renderer/vertex/VertexFormat;", true);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            Label l11 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l11);
            Label l12 = new Label();
            methodVisitor.visitLabel(l12);
            methodVisitor.visitLineNumber(51, l12);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitInsn(IALOAD);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            Label l13 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPEQ, l13);
            Label l14 = new Label();
            methodVisitor.visitLabel(l14);
            methodVisitor.visitLineNumber(52, l14);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitInsn(IALOAD);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "put", "(I[F)V", true);
            Label l15 = new Label();
            methodVisitor.visitJumpInsn(GOTO, l15);
            methodVisitor.visitLabel(l13);
            methodVisitor.visitLineNumber(54, l13);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitIntInsn(NEWARRAY, T_FLOAT);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "net/minecraftforge/client/model/pipeline/IVertexConsumer", "put", "(I[F)V", true);
            methodVisitor.visitLabel(l15);
            methodVisitor.visitLineNumber(50, l15);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitIincInsn(4, 1);
            methodVisitor.visitJumpInsn(GOTO, l10);
            methodVisitor.visitLabel(l11);
            methodVisitor.visitLineNumber(49, l11);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitIincInsn(3, 1);
            methodVisitor.visitJumpInsn(GOTO, l7);
            methodVisitor.visitLabel(l8);
            methodVisitor.visitLineNumber(58, l8);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label l16 = new Label();
            methodVisitor.visitLabel(l16);
            methodVisitor.visitLocalVariable("e", "I", null, l10, l11, 4);
            methodVisitor.visitLocalVariable("v", "I", null, l7, l8, 3);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l16, 0);
            methodVisitor.visitLocalVariable("consumer", "Lnet/minecraftforge/client/model/pipeline/IVertexConsumer;", null, l0, l16, 1);
            methodVisitor.visitLocalVariable("eMap", "[I", null, l1, l16, 2);
            methodVisitor.visitMaxs(5, 5);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, LoliLoadingPlugin.isDeobf ? "hasTintIndex" : "func_178212_b", "()Z", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(62, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "tint", "B");
            methodVisitor.visitInsn(ICONST_M1);
            Label l1 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPEQ, l1);
            methodVisitor.visitInsn(ICONST_1);
            Label l2 = new Label();
            methodVisitor.visitJumpInsn(GOTO, l2);
            methodVisitor.visitLabel(l1);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitLabel(l2);
            methodVisitor.visitFrame(F_SAME1, 0, null, 1, new Object[]{INTEGER});
            methodVisitor.visitInsn(IRETURN);
            Label l3 = new Label();
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l3, 0);
            methodVisitor.visitMaxs(2, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, LoliLoadingPlugin.isDeobf ? "getTintIndex" : "func_178211_c", "()I", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(67, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "tint", "B");
            methodVisitor.visitInsn(IRETURN);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, LoliLoadingPlugin.isDeobf ? "getFace" : "func_178210_d", "()Lnet/minecraft/util/EnumFacing;", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(72, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "orientation", "Lnet/minecraft/util/EnumFacing;");
            methodVisitor.visitInsn(ARETURN);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "shouldApplyDiffuseLighting", "()Z", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(77, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "applyDiffuseLighting", "Z");
            methodVisitor.visitInsn(IRETURN);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, l0, l1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        writer.visitEnd();
        return writer.toByteArray();
    }

    public static byte[] rewriteUnpackedBakedQuad$Builder(byte[] originalClass) {
        ClassWriter writer = new ClassWriter(0);
        FieldVisitor fieldVisitor;
        MethodVisitor methodVisitor;

        writer.visit(52, ACC_PUBLIC | ACC_SUPER, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", null, "java/lang/Object", new String[]{"net/minecraftforge/client/model/pipeline/IVertexConsumer"});

        writer.visitSource("UnpackedBakedQuad.java", null);

        writer.visitInnerClass("net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "Builder", ACC_PUBLIC | ACC_STATIC);
        writer.visitInnerClass("net/minecraft/client/renderer/vertex/VertexFormatElement$EnumUsage", "net/minecraft/client/renderer/vertex/VertexFormatElement", "EnumUsage", ACC_PUBLIC | ACC_FINAL | ACC_STATIC | ACC_ENUM);

        {
            fieldVisitor = writer.visitField(ACC_PRIVATE | ACC_FINAL, "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE | ACC_FINAL, "unpackedData", "[[[F", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "tint", "I", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "orientation", "Lnet/minecraft/util/EnumFacing;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "applyDiffuseLighting", "Z", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "vertices", "I", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "elements", "I", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "full", "Z", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE, "contractUVs", "Z", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = writer.visitField(ACC_PRIVATE | ACC_FINAL, "eps", "F", null, new Float("0.00390625"));
            fieldVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "<init>", "(Lnet/minecraft/client/renderer/vertex/VertexFormat;)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(94, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(84, l1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_M1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "tint", "I");
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLineNumber(87, l2);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "applyDiffuseLighting", "Z");
            Label l3 = new Label();
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLineNumber(89, l3);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "vertices", "I");
            Label l4 = new Label();
            methodVisitor.visitLabel(l4);
            methodVisitor.visitLineNumber(90, l4);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "elements", "I");
            Label l5 = new Label();
            methodVisitor.visitLabel(l5);
            methodVisitor.visitLineNumber(91, l5);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "full", "Z");
            Label l6 = new Label();
            methodVisitor.visitLabel(l6);
            methodVisitor.visitLineNumber(92, l6);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "contractUVs", "Z");
            Label l7 = new Label();
            methodVisitor.visitLabel(l7);
            methodVisitor.visitLineNumber(149, l7);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitLdcInsn(new Float("0.00390625"));
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "eps", "F");
            Label l8 = new Label();
            methodVisitor.visitLabel(l8);
            methodVisitor.visitLineNumber(95, l8);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            Label l9 = new Label();
            methodVisitor.visitLabel(l9);
            methodVisitor.visitLineNumber(96, l9);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_4);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            methodVisitor.visitInsn(ICONST_4);
            methodVisitor.visitMultiANewArrayInsn("[[[F", 3);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            Label l10 = new Label();
            methodVisitor.visitLabel(l10);
            methodVisitor.visitLineNumber(97, l10);
            methodVisitor.visitInsn(RETURN);
            Label l11 = new Label();
            methodVisitor.visitLabel(l11);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l11, 0);
            methodVisitor.visitLocalVariable("format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;", null, l0, l11, 1);
            methodVisitor.visitMaxs(4, 2);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "getVertexFormat", "()Lnet/minecraft/client/renderer/vertex/VertexFormat;", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(101, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitInsn(ARETURN);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "setContractUVs", "(Z)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(105, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "contractUVs", "Z");
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(106, l1);
            methodVisitor.visitInsn(RETURN);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l2, 0);
            methodVisitor.visitLocalVariable("value", "Z", null, l0, l2, 1);
            methodVisitor.visitMaxs(2, 2);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "setQuadTint", "(I)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(110, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "tint", "I");
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(111, l1);
            methodVisitor.visitInsn(RETURN);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l2, 0);
            methodVisitor.visitLocalVariable("tint", "I", null, l0, l2, 1);
            methodVisitor.visitMaxs(2, 2);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "setQuadOrientation", "(Lnet/minecraft/util/EnumFacing;)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(115, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "orientation", "Lnet/minecraft/util/EnumFacing;");
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(116, l1);
            methodVisitor.visitInsn(RETURN);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l2, 0);
            methodVisitor.visitLocalVariable("orientation", "Lnet/minecraft/util/EnumFacing;", null, l0, l2, 1);
            methodVisitor.visitMaxs(2, 2);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "setTexture", "(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(121, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(122, l1);
            methodVisitor.visitInsn(RETURN);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l2, 0);
            methodVisitor.visitLocalVariable("texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;", null, l0, l2, 1);
            methodVisitor.visitMaxs(2, 2);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "setApplyDiffuseLighting", "(Z)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(126, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "applyDiffuseLighting", "Z");
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(127, l1);
            methodVisitor.visitInsn(RETURN);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l2, 0);
            methodVisitor.visitLocalVariable("diffuse", "Z", null, l0, l2, 1);
            methodVisitor.visitMaxs(2, 2);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC | ACC_VARARGS, "put", "(I[F)V", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(131, l0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 3);
            Label l1 = new Label();
            methodVisitor.visitLabel(l1);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitInsn(ICONST_4);
            Label l2 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l2);
            Label l3 = new Label();
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLineNumber(132, l3);
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitInsn(ARRAYLENGTH);
            Label l4 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l4);
            Label l5 = new Label();
            methodVisitor.visitLabel(l5);
            methodVisitor.visitLineNumber(133, l5);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "vertices", "I");
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitInsn(FASTORE);
            Label l6 = new Label();
            methodVisitor.visitJumpInsn(GOTO, l6);
            methodVisitor.visitLabel(l4);
            methodVisitor.visitLineNumber(135, l4);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "vertices", "I");
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 3);
            methodVisitor.visitInsn(FCONST_0);
            methodVisitor.visitInsn(FASTORE);
            methodVisitor.visitLabel(l6);
            methodVisitor.visitLineNumber(131, l6);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitIincInsn(3, 1);
            methodVisitor.visitJumpInsn(GOTO, l1);
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLineNumber(138, l2);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "elements", "I");
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitInsn(IADD);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "elements", "I");
            Label l7 = new Label();
            methodVisitor.visitLabel(l7);
            methodVisitor.visitLineNumber(139, l7);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "elements", "I");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            Label l8 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPNE, l8);
            Label l9 = new Label();
            methodVisitor.visitLabel(l9);
            methodVisitor.visitLineNumber(140, l9);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "vertices", "I");
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitInsn(IADD);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "vertices", "I");
            Label l10 = new Label();
            methodVisitor.visitLabel(l10);
            methodVisitor.visitLineNumber(141, l10);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "elements", "I");
            methodVisitor.visitLabel(l8);
            methodVisitor.visitLineNumber(143, l8);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "vertices", "I");
            methodVisitor.visitInsn(ICONST_4);
            Label l11 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPNE, l11);
            Label l12 = new Label();
            methodVisitor.visitLabel(l12);
            methodVisitor.visitLineNumber(145, l12);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "full", "Z");
            methodVisitor.visitLabel(l11);
            methodVisitor.visitLineNumber(147, l11);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label l13 = new Label();
            methodVisitor.visitLabel(l13);
            methodVisitor.visitLocalVariable("i", "I", null, l1, l2, 3);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l13, 0);
            methodVisitor.visitLocalVariable("element", "I", null, l0, l13, 1);
            methodVisitor.visitLocalVariable("data", "[F", null, l0, l13, 2);
            methodVisitor.visitMaxs(4, 4);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = writer.visitMethod(ACC_PUBLIC, "build", "()Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad;", null, null);
            methodVisitor.visitCode();
            Label l0 = new Label();
            methodVisitor.visitLabel(l0);
            methodVisitor.visitLineNumber(152, l0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "full", "Z");
            Label l1 = new Label();
            methodVisitor.visitJumpInsn(IFNE, l1);
            Label l2 = new Label();
            methodVisitor.visitLabel(l2);
            methodVisitor.visitLineNumber(153, l2);
            methodVisitor.visitTypeInsn(NEW, "java/lang/IllegalStateException");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitLdcInsn("not enough data");
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/IllegalStateException", "<init>", "(Ljava/lang/String;)V", false);
            methodVisitor.visitInsn(ATHROW);
            methodVisitor.visitLabel(l1);
            methodVisitor.visitLineNumber(155, l1);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            Label l3 = new Label();
            methodVisitor.visitJumpInsn(IFNONNULL, l3);
            Label l4 = new Label();
            methodVisitor.visitLabel(l4);
            methodVisitor.visitLineNumber(156, l4);
            methodVisitor.visitTypeInsn(NEW, "java/lang/IllegalStateException");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitLdcInsn("texture not set");
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/IllegalStateException", "<init>", "(Ljava/lang/String;)V", false);
            methodVisitor.visitInsn(ATHROW);
            methodVisitor.visitLabel(l3);
            methodVisitor.visitLineNumber(158, l3);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "contractUVs", "Z");
            Label l5 = new Label();
            methodVisitor.visitJumpInsn(IFEQ, l5);
            Label l6 = new Label();
            methodVisitor.visitLabel(l6);
            methodVisitor.visitLineNumber(159, l6);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureAtlasSprite", LoliLoadingPlugin.isDeobf ? "getIconWidth" : "func_94211_a", "()I", false);
            methodVisitor.visitInsn(I2F);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureAtlasSprite", LoliLoadingPlugin.isDeobf ? "getMaxU" : "func_94212_f", "()F", false);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureAtlasSprite", LoliLoadingPlugin.isDeobf ? "getMinU" : "func_94209_e", "()F", false);
            methodVisitor.visitInsn(FSUB);
            methodVisitor.visitInsn(FDIV);
            methodVisitor.visitVarInsn(FSTORE, 1);
            Label l7 = new Label();
            methodVisitor.visitLabel(l7);
            methodVisitor.visitLineNumber(160, l7);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureAtlasSprite", LoliLoadingPlugin.isDeobf ? "getIconHeight" : "func_94216_b", "()I", false);
            methodVisitor.visitInsn(I2F);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureAtlasSprite", LoliLoadingPlugin.isDeobf ? "getMaxV" : "func_94210_h", "()F", false);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureAtlasSprite", LoliLoadingPlugin.isDeobf ? "getMinV" : "func_94206_g", "()F", false);
            methodVisitor.visitInsn(FSUB);
            methodVisitor.visitInsn(FDIV);
            methodVisitor.visitVarInsn(FSTORE, 2);
            Label l8 = new Label();
            methodVisitor.visitLabel(l8);
            methodVisitor.visitLineNumber(161, l8);
            methodVisitor.visitVarInsn(FLOAD, 1);
            methodVisitor.visitVarInsn(FLOAD, 2);
            methodVisitor.visitInsn(FCMPL);
            Label l9 = new Label();
            methodVisitor.visitJumpInsn(IFLE, l9);
            methodVisitor.visitVarInsn(FLOAD, 1);
            Label l10 = new Label();
            methodVisitor.visitJumpInsn(GOTO, l10);
            methodVisitor.visitLabel(l9);
            methodVisitor.visitFrame(F_APPEND, 2, new Object[]{FLOAT, FLOAT}, 0, null);
            methodVisitor.visitVarInsn(FLOAD, 2);
            methodVisitor.visitLabel(l10);
            methodVisitor.visitFrame(F_SAME1, 0, null, 1, new Object[]{FLOAT});
            methodVisitor.visitVarInsn(FSTORE, 3);
            Label l11 = new Label();
            methodVisitor.visitLabel(l11);
            methodVisitor.visitLineNumber(162, l11);
            methodVisitor.visitInsn(FCONST_1);
            methodVisitor.visitVarInsn(FLOAD, 3);
            methodVisitor.visitLdcInsn(new Float("256.0"));
            methodVisitor.visitInsn(FMUL);
            methodVisitor.visitInsn(FDIV);
            methodVisitor.visitVarInsn(FSTORE, 4);
            Label l12 = new Label();
            methodVisitor.visitLabel(l12);
            methodVisitor.visitLineNumber(163, l12);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 5);
            Label l13 = new Label();
            methodVisitor.visitLabel(l13);
            methodVisitor.visitLineNumber(164, l13);
            methodVisitor.visitFrame(F_APPEND, 3, new Object[]{FLOAT, FLOAT, INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            Label l14 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l14);
            Label l15 = new Label();
            methodVisitor.visitLabel(l15);
            methodVisitor.visitLineNumber(165, l15);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElement" : "func_177348_c", "(I)Lnet/minecraft/client/renderer/vertex/VertexFormatElement;", false);
            methodVisitor.visitVarInsn(ASTORE, 6);
            Label l16 = new Label();
            methodVisitor.visitLabel(l16);
            methodVisitor.visitLineNumber(166, l16);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormatElement", LoliLoadingPlugin.isDeobf ? "getUsage" : "func_177375_c", "()Lnet/minecraft/client/renderer/vertex/VertexFormatElement$EnumUsage;", false);
            methodVisitor.visitFieldInsn(GETSTATIC, "net/minecraft/client/renderer/vertex/VertexFormatElement$EnumUsage", "UV", "Lnet/minecraft/client/renderer/vertex/VertexFormatElement$EnumUsage;");
            Label l17 = new Label();
            methodVisitor.visitJumpInsn(IF_ACMPNE, l17);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormatElement", LoliLoadingPlugin.isDeobf ? "getIndex" : "func_177369_e", "()I", false);
            methodVisitor.visitJumpInsn(IFNE, l17);
            Label l18 = new Label();
            methodVisitor.visitLabel(l18);
            methodVisitor.visitLineNumber(167, l18);
            methodVisitor.visitJumpInsn(GOTO, l14);
            methodVisitor.visitLabel(l17);
            methodVisitor.visitLineNumber(169, l17);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{"net/minecraft/client/renderer/vertex/VertexFormatElement"}, 0, null);
            methodVisitor.visitIincInsn(5, 1);
            Label l19 = new Label();
            methodVisitor.visitLabel(l19);
            methodVisitor.visitLineNumber(170, l19);
            methodVisitor.visitJumpInsn(GOTO, l13);
            methodVisitor.visitLabel(l14);
            methodVisitor.visitLineNumber(171, l14);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/vertex/VertexFormat", LoliLoadingPlugin.isDeobf ? "getElementCount" : "func_177345_h", "()I", false);
            Label l20 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPNE, l20);
            Label l21 = new Label();
            methodVisitor.visitLabel(l21);
            methodVisitor.visitLineNumber(172, l21);
            methodVisitor.visitTypeInsn(NEW, "java/lang/IllegalStateException");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitLdcInsn("Can't contract UVs: format doesn't contain UVs");
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/IllegalStateException", "<init>", "(Ljava/lang/String;)V", false);
            methodVisitor.visitInsn(ATHROW);
            methodVisitor.visitLabel(l20);
            methodVisitor.visitLineNumber(174, l20);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(ICONST_4);
            methodVisitor.visitIntInsn(NEWARRAY, T_FLOAT);
            methodVisitor.visitVarInsn(ASTORE, 6);
            Label l22 = new Label();
            methodVisitor.visitLabel(l22);
            methodVisitor.visitLineNumber(175, l22);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 7);
            Label l23 = new Label();
            methodVisitor.visitLabel(l23);
            methodVisitor.visitFrame(F_APPEND, 2, new Object[]{"[F", INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 7);
            methodVisitor.visitInsn(ICONST_4);
            Label l24 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l24);
            Label l25 = new Label();
            methodVisitor.visitLabel(l25);
            methodVisitor.visitLineNumber(176, l25);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 8);
            Label l26 = new Label();
            methodVisitor.visitLabel(l26);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(ICONST_4);
            Label l27 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l27);
            Label l28 = new Label();
            methodVisitor.visitLabel(l28);
            methodVisitor.visitLineNumber(177, l28);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(DUP2);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ILOAD, 7);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitLdcInsn(new Float("4.0"));
            methodVisitor.visitInsn(FDIV);
            methodVisitor.visitInsn(FADD);
            methodVisitor.visitInsn(FASTORE);
            Label l29 = new Label();
            methodVisitor.visitLabel(l29);
            methodVisitor.visitLineNumber(176, l29);
            methodVisitor.visitIincInsn(8, 1);
            methodVisitor.visitJumpInsn(GOTO, l26);
            methodVisitor.visitLabel(l27);
            methodVisitor.visitLineNumber(175, l27);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitIincInsn(7, 1);
            methodVisitor.visitJumpInsn(GOTO, l23);
            methodVisitor.visitLabel(l24);
            methodVisitor.visitLineNumber(180, l24);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 7);
            Label l30 = new Label();
            methodVisitor.visitLabel(l30);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 7);
            methodVisitor.visitInsn(ICONST_4);
            methodVisitor.visitJumpInsn(IF_ICMPGE, l5);
            Label l31 = new Label();
            methodVisitor.visitLabel(l31);
            methodVisitor.visitLineNumber(181, l31);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitVarInsn(ISTORE, 8);
            Label l32 = new Label();
            methodVisitor.visitLabel(l32);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(ICONST_4);
            Label l33 = new Label();
            methodVisitor.visitJumpInsn(IF_ICMPGE, l33);
            Label l34 = new Label();
            methodVisitor.visitLabel(l34);
            methodVisitor.visitLineNumber(182, l34);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ILOAD, 7);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitVarInsn(FSTORE, 9);
            Label l35 = new Label();
            methodVisitor.visitLabel(l35);
            methodVisitor.visitLineNumber(183, l35);
            methodVisitor.visitVarInsn(FLOAD, 9);
            methodVisitor.visitLdcInsn(new Float("0.99609375"));
            methodVisitor.visitInsn(FMUL);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitLdcInsn(new Float("0.00390625"));
            methodVisitor.visitInsn(FMUL);
            methodVisitor.visitInsn(FADD);
            methodVisitor.visitVarInsn(FSTORE, 10);
            Label l36 = new Label();
            methodVisitor.visitLabel(l36);
            methodVisitor.visitLineNumber(184, l36);
            methodVisitor.visitVarInsn(FLOAD, 9);
            methodVisitor.visitVarInsn(FLOAD, 10);
            methodVisitor.visitInsn(FSUB);
            methodVisitor.visitVarInsn(FSTORE, 11);
            Label l37 = new Label();
            methodVisitor.visitLabel(l37);
            methodVisitor.visitLineNumber(185, l37);
            methodVisitor.visitVarInsn(FLOAD, 11);
            methodVisitor.visitVarInsn(FSTORE, 12);
            Label l38 = new Label();
            methodVisitor.visitLabel(l38);
            methodVisitor.visitLineNumber(186, l38);
            methodVisitor.visitVarInsn(FLOAD, 12);
            methodVisitor.visitInsn(FCONST_0);
            methodVisitor.visitInsn(FCMPG);
            Label l39 = new Label();
            methodVisitor.visitJumpInsn(IFGE, l39);
            Label l40 = new Label();
            methodVisitor.visitLabel(l40);
            methodVisitor.visitLineNumber(187, l40);
            methodVisitor.visitVarInsn(FLOAD, 12);
            methodVisitor.visitInsn(FNEG);
            methodVisitor.visitVarInsn(FSTORE, 12);
            methodVisitor.visitLabel(l39);
            methodVisitor.visitLineNumber(189, l39);
            methodVisitor.visitFrame(F_FULL, 13, new Object[]{"net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", FLOAT, FLOAT, FLOAT, FLOAT, INTEGER, "[F", INTEGER, INTEGER, FLOAT, FLOAT, FLOAT, FLOAT}, 0, new Object[]{});
            methodVisitor.visitVarInsn(FLOAD, 12);
            methodVisitor.visitVarInsn(FLOAD, 4);
            methodVisitor.visitInsn(FCMPG);
            Label l41 = new Label();
            methodVisitor.visitJumpInsn(IFGE, l41);
            Label l42 = new Label();
            methodVisitor.visitLabel(l42);
            methodVisitor.visitLineNumber(190, l42);
            methodVisitor.visitVarInsn(FLOAD, 9);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitInsn(FSUB);
            methodVisitor.visitVarInsn(FSTORE, 13);
            Label l43 = new Label();
            methodVisitor.visitLabel(l43);
            methodVisitor.visitLineNumber(191, l43);
            methodVisitor.visitVarInsn(FLOAD, 13);
            methodVisitor.visitInsn(FCONST_0);
            methodVisitor.visitInsn(FCMPG);
            Label l44 = new Label();
            methodVisitor.visitJumpInsn(IFGE, l44);
            Label l45 = new Label();
            methodVisitor.visitLabel(l45);
            methodVisitor.visitLineNumber(192, l45);
            methodVisitor.visitVarInsn(FLOAD, 13);
            methodVisitor.visitInsn(FNEG);
            methodVisitor.visitVarInsn(FSTORE, 13);
            methodVisitor.visitLabel(l44);
            methodVisitor.visitLineNumber(194, l44);
            methodVisitor.visitFrame(F_APPEND, 1, new Object[]{FLOAT}, 0, null);
            methodVisitor.visitVarInsn(FLOAD, 13);
            methodVisitor.visitInsn(FCONST_2);
            methodVisitor.visitVarInsn(FLOAD, 4);
            methodVisitor.visitInsn(FMUL);
            methodVisitor.visitInsn(FCMPG);
            Label l46 = new Label();
            methodVisitor.visitJumpInsn(IFGE, l46);
            Label l47 = new Label();
            methodVisitor.visitLabel(l47);
            methodVisitor.visitLineNumber(195, l47);
            methodVisitor.visitVarInsn(FLOAD, 9);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitInsn(FALOAD);
            methodVisitor.visitInsn(FADD);
            methodVisitor.visitInsn(FCONST_2);
            methodVisitor.visitInsn(FDIV);
            methodVisitor.visitVarInsn(FSTORE, 10);
            methodVisitor.visitJumpInsn(GOTO, l41);
            methodVisitor.visitLabel(l46);
            methodVisitor.visitLineNumber(197, l46);
            methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(FLOAD, 9);
            methodVisitor.visitVarInsn(FLOAD, 11);
            methodVisitor.visitInsn(FCONST_0);
            methodVisitor.visitInsn(FCMPG);
            Label l48 = new Label();
            methodVisitor.visitJumpInsn(IFGE, l48);
            methodVisitor.visitVarInsn(FLOAD, 4);
            Label l49 = new Label();
            methodVisitor.visitJumpInsn(GOTO, l49);
            methodVisitor.visitLabel(l48);
            methodVisitor.visitFrame(F_SAME1, 0, null, 1, new Object[]{FLOAT});
            methodVisitor.visitVarInsn(FLOAD, 4);
            methodVisitor.visitInsn(FNEG);
            methodVisitor.visitLabel(l49);
            methodVisitor.visitFrame(F_FULL, 14, new Object[]{"net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", FLOAT, FLOAT, FLOAT, FLOAT, INTEGER, "[F", INTEGER, INTEGER, FLOAT, FLOAT, FLOAT, FLOAT, FLOAT}, 2, new Object[]{FLOAT, FLOAT});
            methodVisitor.visitInsn(FADD);
            methodVisitor.visitVarInsn(FSTORE, 10);
            methodVisitor.visitLabel(l41);
            methodVisitor.visitLineNumber(200, l41);
            methodVisitor.visitFrame(F_CHOP, 1, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ILOAD, 7);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitInsn(AALOAD);
            methodVisitor.visitVarInsn(ILOAD, 8);
            methodVisitor.visitVarInsn(FLOAD, 10);
            methodVisitor.visitInsn(FASTORE);
            Label l50 = new Label();
            methodVisitor.visitLabel(l50);
            methodVisitor.visitLineNumber(181, l50);
            methodVisitor.visitIincInsn(8, 1);
            methodVisitor.visitJumpInsn(GOTO, l32);
            methodVisitor.visitLabel(l33);
            methodVisitor.visitLineNumber(180, l33);
            methodVisitor.visitFrame(F_FULL, 8, new Object[]{"net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", FLOAT, FLOAT, FLOAT, FLOAT, INTEGER, "[F", INTEGER}, 0, new Object[]{});
            methodVisitor.visitIincInsn(7, 1);
            methodVisitor.visitJumpInsn(GOTO, l30);
            methodVisitor.visitLabel(l5);
            methodVisitor.visitLineNumber(204, l5);
            methodVisitor.visitFrame(F_FULL, 1, new Object[]{"net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder"}, 0, new Object[]{});
            methodVisitor.visitTypeInsn(NEW, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "unpackedData", "[[[F");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "tint", "I");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "orientation", "Lnet/minecraft/util/EnumFacing;");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "texture", "Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "applyDiffuseLighting", "Z");
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder", "format", "Lnet/minecraft/client/renderer/vertex/VertexFormat;");
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "net/minecraftforge/client/model/pipeline/UnpackedBakedQuad", "<init>", "([[[FILnet/minecraft/util/EnumFacing;Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;ZLnet/minecraft/client/renderer/vertex/VertexFormat;)V", false);
            methodVisitor.visitInsn(ARETURN);
            Label l51 = new Label();
            methodVisitor.visitLabel(l51);
            methodVisitor.visitLocalVariable("e", "Lnet/minecraft/client/renderer/vertex/VertexFormatElement;", null, l16, l19, 6);
            methodVisitor.visitLocalVariable("i", "I", null, l26, l27, 8);
            methodVisitor.visitLocalVariable("v", "I", null, l23, l24, 7);
            methodVisitor.visitLocalVariable("udc", "F", null, l43, l41, 13);
            methodVisitor.visitLocalVariable("uo", "F", null, l35, l50, 9);
            methodVisitor.visitLocalVariable("un", "F", null, l36, l50, 10);
            methodVisitor.visitLocalVariable("ud", "F", null, l37, l50, 11);
            methodVisitor.visitLocalVariable("aud", "F", null, l38, l50, 12);
            methodVisitor.visitLocalVariable("i", "I", null, l32, l33, 8);
            methodVisitor.visitLocalVariable("v", "I", null, l30, l5, 7);
            methodVisitor.visitLocalVariable("tX", "F", null, l7, l5, 1);
            methodVisitor.visitLocalVariable("tY", "F", null, l8, l5, 2);
            methodVisitor.visitLocalVariable("tS", "F", null, l11, l5, 3);
            methodVisitor.visitLocalVariable("ep", "F", null, l12, l5, 4);
            methodVisitor.visitLocalVariable("uve", "I", null, l13, l5, 5);
            methodVisitor.visitLocalVariable("uvc", "[F", null, l22, l5, 6);
            methodVisitor.visitLocalVariable("this", "Lnet/minecraftforge/client/model/pipeline/UnpackedBakedQuad$Builder;", null, l0, l51, 0);
            methodVisitor.visitMaxs(8, 14);
            methodVisitor.visitEnd();
        }
        writer.visitEnd();

        return writer.toByteArray();
    }
    
    private UnpackedBakedQuadPatch() { }

}
